"""
Conversation model for storing AI conversation history.
"""

from typing import Optional
from uuid import UUID

from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import BaseModel


class Conversation(BaseModel):
    """
    Conversation model for storing AI conversation history.

    Stores:
    - Complete message history for the conversation
    - Conversation summary
    - Detected intent and sentiment
    - Associated call record
    """

    __tablename__ = "conversations"

    # Associated call
    call_id: Mapped[UUID] = mapped_column(
        ForeignKey("calls.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Message history
    # Format: [{"role": "user"|"assistant"|"system", "content": str, "timestamp": str}, ...]
    messages: Mapped[list[dict]] = mapped_column(JSON, nullable=False, default=list)

    # Conversation summary (generated by AI)
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Intent detection
    intent: Mapped[Optional[str]] = mapped_column(String(100), nullable=True, index=True)

    # Sentiment analysis
    sentiment: Mapped[Optional[str]] = mapped_column(
        String(50), nullable=True, index=True
    )

    # Additional metadata
    metadata: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True, default=dict)

    # Relationships
    call: Mapped["Call"] = relationship("Call", back_populates="conversations")

    def __repr__(self) -> str:
        return (
            f"Conversation(id={self.id}, call_id={self.call_id}, "
            f"messages={len(self.messages)}, intent={self.intent})"
        )

    def add_message(self, role: str, content: str) -> None:
        """
        Add a message to the conversation history.

        Args:
            role: Message role ("user", "assistant", or "system")
            content: Message content
        """
        from datetime import datetime

        if self.messages is None:
            self.messages = []

        self.messages.append({
            "role": role,
            "content": content,
            "timestamp": datetime.utcnow().isoformat(),
        })

    def get_messages_for_llm(self) -> list[dict[str, str]]:
        """
        Get messages in format suitable for LLM API calls.

        Returns:
            List of messages with role and content
        """
        return [
            {"role": msg["role"], "content": msg["content"]}
            for msg in (self.messages or [])
        ]
